[project]
name = "chatacter_app"
version = "0.1.0"
description = "App part of the Chatacter Backend"
readme = "README.md"
authors = [
    { name = "Mohamed Hisham Abdelzaher", email = "mohamed.hisham.abdelzaher@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "qdrant-client[fastembed-gpu]>=1.11.1",
]

[project.scripts]
App = "App:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.typos.default.extend-words]
chatacter = "chatacter"
